// Data
export const FETCH_RESUME_DATA_BEGIN = 'FETCH_RESUME_DATA_BEGIN';
export const FETCH_RESUME_DATA_SUCCESS = 'FETCH_RESUME_DATA_SUCCESS';
export const FETCH_RESUME_DATA_FAILURE = 'FETCH_RESUME_DATA_FAILURE';

// Anything related to resume input
export const UPDATE_RESUME_FORM_INPUT = 'UPDATE_RESUME_FORM_INPUT';

// Skill Info
export const ADD_SKILL = 'ADD_SKILL';
export const REMOVE_SKILL = 'REMOVE_SKILL';
export const ADD_SKILL_CATEGORY = 'ADD_SKILL_CATEGORY';
export const REMOVE_SKILL_CATEGORY = 'REMOVE_SKILL_CATEGORY';
