// Data
export const FETCH_RESUME_DATA_BEGIN = 'FETCH_RESUME_DATA_BEGIN';
export const FETCH_RESUME_DATA_SUCCESS = 'FETCH_RESUME_DATA_SUCCESS';
export const FETCH_RESUME_DATA_FAILURE = 'FETCH_RESUME_DATA_FAILURE';

// Basic Info
export const UPDATE_BASIC_INFO_FORM = 'UPDATE_BASIC_INFO_FORM';
